name: Scheduled Entity Linking

on:
  schedule:
    # Run every 30 minutes from 16:30 to 23:30 UTC daily
    - cron: '30,0 16-23 * * *'
    # Run at 00:00 and 00:30 UTC daily
    - cron: '0,30 0 * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  run-entity-linking:
    name: Run LLM Entity Linking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LLM Entity Linking
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python scripts/llm_entity_linker_cli.py run --batch-size 20 --max-batches 20
